### ISSUE TITLE
Rescan files that throw an error

### ISSUE THREAD

**Issue by aviral-batra** [aviral-batra/Obsidian_to_Anki#1]
When a file throws an error, it is added to the list of scanned files but the cards are not actually scanned. Prevent this from happening.

**Comment by ayyubshaffy7** [comment]
hey , I'm coming from the Pseudonium's GitHub page. Were you able to fix this issue ?

![Pasted image 20220311103904](https://user-images.githubusercontent.com/44515527/158576273-05179db2-22da-4951-826f-fbff75b0bb0f.png)
Relatedly there's also some bugs when the hash ID is shown like above but the card isn't created in Anki. What I have to do is to DELETE the card and re-scan it. So now I have to keep track of when some cards aren't created which is frankly annoying with bulk uploads.

**Comment by aviral-batra** [comment]
> hey , I'm coming from the Pseudonium's GitHub page. Were you able to fix this issue ?
> 
> ![Pasted image 20220311103904](https://user-images.githubusercontent.com/44515527/158576273-05179db2-22da-4951-826f-fbff75b0bb0f.png) Relatedly there's also some bugs when the hash ID is shown like above but the card isn't created in Anki. What I have to do is to DELETE the card and re-scan it. So now I have to keep track of when some cards aren't created which is frankly annoying with bulk uploads.

I have done this by the way.
